services:
  OxidEsales\EshopCommunity\Internal\Templating\TraditionalEngineInterface:
    class: OxidEsales\EshopCommunity\Internal\Templating\TraditionalEngine
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Twig\TwigEngine'
      - '@OxidEsales\EshopCommunity\Internal\Templating\TemplateNameResolverInterface'
    public: true
    tags: ['templating']
  OxidEsales\EshopCommunity\Internal\Templating\TemplateNameResolverInterface:
    class: OxidEsales\EshopCommunity\Internal\Templating\LegacyTemplateNameResolver
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Templating\TemplateNameResolver'
  OxidEsales\EshopCommunity\Internal\Templating\TemplateNameResolver:
    class: OxidEsales\EshopCommunity\Internal\Templating\TemplateNameResolver