
services:

  OxidEsales\EshopCommunity\Internal\Module\Configuration\Bridge\ModuleConfigurationDaoBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Configuration\Bridge\ModuleConfigurationDaoBridge
    autowire: true
    public: true

  OxidEsales\EshopCommunity\Internal\Module\Configuration\Bridge\ShopConfigurationDaoBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Configuration\Bridge\ShopConfigurationDaoBridge
    autowire: true
    public: true

  OxidEsales\EshopCommunity\Internal\Module\Configuration\Bridge\EnvironmentConfigurationBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Configuration\Bridge\EnvironmentConfigurationBridge
    autowire: true
    public: true